### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by typ0520** [sensorsdata/sa-sdk-android-plugin#1]
神策的插件是把JarMerging这个任务干掉了吗？  DirectoryInput和JarInput内容都被替换掉了，导致我们之前加的别的插件用不了

**Comment by wangzhzh** [comment]
具体是哪个插件用不了？我们分析一下原因

**Comment by typ0520** [comment]
[fastdex](https://github.com/typ0520/fastdex),  应该是神策的插件改变了原有的打包流程导致的

**Comment by wangzhzh** [comment]
我们近期会更新一个版本来解决这个问题

**Comment by typ0520** [comment]
好的,麻烦了

**Comment by wangzhzh** [comment]
按照这个步骤集成试试，注意插件和SDK中的数字2:

第一步：在 project 级别的 build.gradle 文件中添加 Sensors Analytics android-gradle-plugin 依赖：

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        //添加 Sensors Analytics android-gradle-plugin 依赖
        classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:1.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
第二步：在 主 module 的 build.gradle 文件中添加 com.sensorsdata.analytics.android 插件、Sensors Analytics SDK 依赖：

apply plugin: 'com.android.application'
//添加 com.sensorsdata.analytics.android 插件
apply plugin: 'com.sensorsdata.analytics.android'

dependencies {
   compile 'com.android.support:appcompat-v7:25.1.1'
   //添加 Sensors Analytics SDK 依赖
   compile 'com.sensorsdata.analytics.android:SensorsAnalyticsSDK2:1.8.0'
}

**Comment by wangzhzh** [comment]
新的插件已 release 正式版
你可以通过如下两个步骤切换到新的插件方案上：
1、在根目录下的 build.gradle 文件里修改引用新的插件：
	classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:1.0.1'
2、在主 module 的 build.gradle 文件里，将我们的 SDK 更新到 1.8.5，即：
	compile 'com.sensorsdata.analytics.android:SensorsAnalyticsSDK:1.8.5'
